### ISSUE TITLE
Markdown rendering image with {attach} attribute fails

### ISSUE THREAD

**Issue by alexandrenorman** [whiskyechobravo/image_process#3]
Rendering the following part: 
```
[picture]({attach}test.jpg "Title"){class="image-process-go-left"}
```

like in http://docs.getpelican.com/en/3.6.3/content.html#attaching-static-files

Fails:

```
CRITICAL: FileNotFoundError: [Errno 2] No such file or directory: '/newsletter/content/{attach}test.jpg'
Traceback (most recent call last):
  File "/home/xael/python.venvs/newsletter/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/home/xael/python.venvs/newsletter/lib/python3.4/site-packages/pelican/__init__.py", line 478, in main
    pelican.run()
  File "/home/xael/python.venvs/newsletter/lib/python3.4/site-packages/pelican/__init__.py", line 185, in run
    signals.finalized.send(self)
  File "/home/xael/python.venvs/newsletter/lib/python3.4/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/xael/python.venvs/newsletter/lib/python3.4/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/newsletter/pelican-plugins/image_process/image_process.py", line 501, in process_images
    i = Image.open(image[0])
  File "/home/xael/python.venvs/newsletter/lib/python3.4/site-packages/PIL/Image.py", line 2249, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/newsletter/content/{attach}test.jpg'
```

Changing process_images:

```
-            i = Image.open(image[0])
+            i = Image.open(image[0].replace('{attach}', ''))
```
and 
```
-            i.save(image[1])
+            i.save(image[1].replace('{attach}', ''))
```
doesn't really help because of the attach method… file is copied in the same directory than html page and is not know at harvesting time.

**Comment by alexandrenorman** [comment]
solution proposal:

```
diff --git a/image_process.py b/image_process.py
index 094bebe..bdfb9f9 100644
--- a/image_process.py
+++ b/image_process.py
@@ -169,18 +169,28 @@ def harvest_images(instance):
         instance.settings['IMAGE_PROCESS_DIR'] = 'derivatives'
 
     if instance._content is not None:
-        instance._content = harvest_images_in_fragment(instance._content, instance.settings)
+        instance._content = harvest_images_in_fragment(
+            instance._content,
+            instance.settings,
+            os.path.dirname(instance.source_path),
+            os.path.dirname(os.path.join(instance.settings['OUTPUT_PATH'], instance.save_as))
+        )
 
     if hasattr(instance, 'metadata'):
         for tag in iter(instance.metadata):
             fragment = getattr(instance, tag)
             if isinstance(fragment, six.string_types):
-                fragment = harvest_images_in_fragment(fragment, instance.settings)
+                fragment = harvest_images_in_fragment(
+                    fragment,
+                    instance.settings,
+                    os.path.dirname(instance.source_path),
+                    os.path.dirname(os.path.join(instance.settings['OUTPUT_PATH'], instance.save_as))
+                )
                 setattr(instance, tag.lower(), fragment)
                 instance.metadata[tag] = fragment
 
 
-def harvest_images_in_fragment(fragment, settings):
+def harvest_images_in_fragment(fragment, settings, path_from=None, path_to_save_to=None):
     fragment_changed = False
     soup = BeautifulSoup(fragment)
 
@@ -202,7 +212,7 @@ def harvest_images_in_fragment(fragment, settings):
                              settings['IMAGE_PROCESS'][derivative]['type'] == 'image'):
 
                     # Single source image specification.
-                    process_img_tag(img, settings, derivative)
+                    process_img_tag(img, settings, derivative, path_from, path_to_save_to)
                     fragment_changed = True
 
                 elif isinstance(settings['IMAGE_PROCESS'][derivative], dict) and \
@@ -233,29 +243,41 @@ def harvest_images_in_fragment(fragment, settings):
         if body:
             new_fragment = '';
             for element in body.children:
-                new_fragment += element.decode()
+                try:
+                    new_fragment += element.decode()
+                except AttributeError:
+                    new_fragment += element
         else:
-            new_fragment = soup.decode()
+            try:
+                new_fragment = soup.decode()
+            except AttributeError:
+                new_fragment += soup
     else:
         new_fragment = fragment
 
     return new_fragment
 
 
-def process_img_tag(img, settings, derivative):
+def process_img_tag(img, settings, derivative, path_from, path_to_save_to):
     url_path, filename = os.path.split(img['src'])
     base_url = os.path.join(url_path, settings['IMAGE_PROCESS_DIR'], derivative)
 
-    source = os.path.join(settings['PATH'], img['src'][1:])
-    output_path, _ = os.path.split(source)
-    base_path = os.path.join(output_path, settings['IMAGE_PROCESS_DIR'], derivative)
-
-    img['src'] = os.path.join(base_url, filename)
-    destination = os.path.join(base_path, filename)
+    filename = filename.replace('{attach}', '')
+    if '{attach}' in img['src'] and path_to_save_to is not None:
+        source = os.path.join(path_from, filename)
+        destination = os.path.join(path_to_save_to, filename)
+    else:
+        source = os.path.join(settings['PATH'], img['src']).replace('{attach}', '')
+        output_path, _ = os.path.split(source)
+        base_path = os.path.join(output_path, settings['IMAGE_PROCESS_DIR'], derivative)
+        img['src'] = os.path.join(base_url, filename)
+        destination = os.path.join(base_path, filename)
+        
     if isinstance(settings['IMAGE_PROCESS'][derivative], list):
         process = settings['IMAGE_PROCESS'][derivative]
     else:
         process = settings['IMAGE_PROCESS'][derivative]['ops']
+
     images.append((source, destination, process))
 
 
@@ -494,8 +516,7 @@ def process_images(p):
         if (p.settings['IMAGE_PROCESS_FORCE']) or \
                 (not os.path.exists(image[1])) or \
                 (os.path.getmtime(image[0]) > os.path.getmtime(image[1])):
-
-            i = Image.open(image[0])
+            i = Image.open(image[0].replace('{attach}', ''))
 
             for step in image[2]:
                 if hasattr(step, '__call__'):
@@ -504,7 +525,7 @@ def process_images(p):
                     elems = step.split(' ')
                     i = basic_ops[elems[0]](i, *(elems[1:]))
 
-            i.save(image[1])
+            i.save(image[1].replace('{attach}', ''))
 
     # Clean up images global for the case where Pelican is running in
     # autoreload mode.
```

**Comment by patrickfournier** [comment]
``harvest_images_in_fragment`` has changed a lot. Support for ``{attached}`` files would require some work. Pull request are welcome  :-)

**Comment by alexandrenorman** [comment]
Hello, pull request done: see https://github.com/whiskyechobravo/image_process/pull/6
And code is better with this version ;-)
