### ISSUE TITLE
BS with lxml fails (Python 3.4.3) on decoding element

### ISSUE THREAD

**Issue by alexandrenorman** [whiskyechobravo/image_process#4]
```
/home/xael/python.venvs/newsletter/lib/python3.4/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))
ERROR: Could not process newsletters/newsletter_09.md
  | AttributeError: 'NavigableString' object has no attribute 'decode'
  |___
  | Traceback (most recent call last):
  |   File "/home/xael/python.venvs/newsletter/lib/python3.4/site-packages/pelican/generators.py", line 514, in generate_context
  |     context_sender=self)
  |   File "/home/xael/python.venvs/newsletter/lib/python3.4/site-packages/pelican/readers.py", line 548, in read_file
  |     context=context)
  |   File "/home/xael/python.venvs/newsletter/lib/python3.4/site-packages/pelican/contents.py", line 149, in __init__
  |     signals.content_object_init.send(self)
  |   File "/home/xael/python.venvs/newsletter/lib/python3.4/site-packages/blinker/base.py", line 267, in send
  |     for receiver in self.receivers_for(sender)]
  |   File "/home/xael/python.venvs/newsletter/lib/python3.4/site-packages/blinker/base.py", line 267, in <listcomp>
  |     for receiver in self.receivers_for(sender)]
  |   File "/home/xael/ESPACE_KM/HESPUL/newsletter/pelican-plugins/image_process/image_process.py", line 172, in harvest_images
  |     instance._content = harvest_images_in_fragment(instance._content, instance.settings)
  |   File "/home/xael/ESPACE_KM/HESPUL/newsletter/pelican-plugins/image_process/image_process.py", line 236, in harvest_images_in_fragment
  |     new_fragment += element.decode()
  |   File "/home/xael/python.venvs/newsletter/lib/python3.4/site-packages/bs4/element.py", line 713, in __getattr__
  |     self.__class__.__name__, attr))
  | AttributeError: 'NavigableString' object has no attribute 'decode'
```

in this case, ```element``` is equal to ```\n```.

Patch proposal :

```
diff --git a/image_process.py b/image_process.py
index 094bebe..96d70fc 100644
--- a/image_process.py
+++ b/image_process.py
@@ -233,9 +233,15 @@ def harvest_images_in_fragment(fragment, settings):
         if body:
             new_fragment = '';
             for element in body.children:
-                new_fragment += element.decode()
+                try:
+                    new_fragment += element.decode()
+                except AttributeError:
+                    new_fragment += element
         else:
-            new_fragment = soup.decode()
+            try:
+                new_fragment = soup.decode()
+            except AttributeError:
+                new_fragment += soup
     else:
         new_fragment = fragment
```

**Comment by patrickfournier** [comment]
Hi Alexandre,
Sorry for the late follow-up. The code has change a lot in ``harvest_images_in_fragment``. Could you please provide an example article that triggers the error? Or could you test against the master branch?

Thanks,

Patrick

**Comment by alexandrenorman** [comment]
Hello Patrick,

Can't reproduce it against the new repository version. I considere it fixed.
You can close this issue.

Thanks,
Alexandre

**Comment by patrickfournier** [comment]
Thanks for the quick followup.
